# Generated by Django 5.2 on 2025-05-15 08:19

import django.db.models.deletion
import invoice_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('VAT', 'VAT'), ('SVAT', 'SVAT'), ('NON-VAT', 'NON-VAT')], default='VAT', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(upload_to=invoice_manager.models.invoice_upload_path),
        ),
    ]
