# Generated by Django 5.2 on 2025-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0003_invoice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
